#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/helmDeployWazuh
- name: Cloner le repo Wazuh Kubernetes
  git:
    repo: "https://github.com/wazuh/wazuh-kubernetes.git"
    dest: "/opt/wazuh-kubernetes"
    version: "main"
  become: yes

- name: Vérifier que le namespace {{ target_tenant }} existe
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ target_tenant }}"
    state: present
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
  become: yes

- name: Déployer Wazuh via chart local
  kubernetes.core.helm:
    name: "wazuh-{{ target_tenant }}"
    chart_ref: "/opt/wazuh-kubernetes/charts/wazuh"
    release_namespace: "{{ target_tenant }}"
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    wait: yes
    timeout: 600
    values:
      indexer:
        replicas: "{{ wazuh_replica_count }}"
      server:
        replicas: "{{ wazuh_replica_count }}"
      dashboard:
        replicas: "{{ wazuh_replica_count }}"
  become: yes