---
- name: Preparation de base (tous les noeuds)
  hosts: all
  become: true
  roles:
    - common

- name: Installation K3s server (master)
  hosts: k3s_master
  become: true
  roles:
    - k3s_master

- name: Installation K3s agent (workers)
  hosts: k3s_workers
  become: true
  roles:
    - k3s_worker

- name: setup helm
  hosts: k3s_master
  become: true 
  roles:
    - helm 

- name: Create namespaces for Wazuh
  hosts: k3s_master
  vars:
    target_tenant: "soc-core"  
  become: true
  roles:
    - manageNamespaces

- name: Deploy Wazuh with Helm
  hosts: k3s_master
  become: true
  roles:
    - helmDeployWazuh


