---
- name: Preparation de base (tous les noeuds)
  hosts: all
  become: true
  roles:
    - common

- name: Installation K3s server (master)
  hosts: k3s_master
  become: true
  roles:
    - k3s_master

- name: Installation K3s agent (workers)
  hosts: k3s_workers
  become: true
  roles:
    - k3s_worker