---
# tasks file for common
# SPDX-License-Identifier: MIT-0

- name: Verifier la structure des dossiers
  ansible.builtin.debug:
    msg: "La structure est prete sur {{ ansible_hostname }}"

- name: Verifier la connectivité de base (Ping)
  ansible.builtin.ping:

- name: Verifier si l'utilisateur peut passer en root (sudo)
  ansible.builtin.command: whoami
  become: yes
  register: sudo_check

- name: Afficher le résultat du test sudo
  ansible.builtin.debug:
    msg: "Connecté sur {{ inventory_hostname }}. Utilisateur root : {{ sudo_check.stdout }}"